[tool.poetry]
name = "mediacollector"
version = "0.1.0"
description = ""
authors = ["Ikey168"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.26.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
